pipeline{
    agent any
    stages{
	stage('拉取Gitea源码') {
            steps {
                git credentialsId: 'gitea-gitops123', url: 'http://localhost:3000/gitea/jwscalculator.git'
            }
        }
        stage('编译源码') {
            steps {
                bat '''mkdir target
		    cd target
                    mkdir classes
                    cd ..\\src\\main\\java
		            javac gitops\\jwscalculator\\*.java gitops\\jwscalculator\\sdk\\*.java gitops\\jwscalculator\\plugins\\*.java -d ..\\..\\..\\target\\classes'''
            }
        }
        stage('生成jar ') {
            steps {
                bat '''cd target\\classes
		    jar cfe jwscalculator.jar gitops.jwscalculator.JwsCalculator gitops'''
            }
        }
        stage('生成密钥'){
            steps{
                bat '''cd target\\classes
		    keytool -genkey -alias mykey -keystore mykeystore.pfx -storetype PKCS12 -keyalg RSA -storepass mystorepass  -validity 365 -keysize 2048 -dname "CN=liudongliang, OU=chzu, L=xxxy, S=chuzhou, O=anhui, C=CH"'''
            }
        }
        stage('签名jar') {
            steps {
                bat '''cd target\\classes
		    jarsigner -keystore myKeystore.pfx jwscalculator.jar mykey -storepass mystorepass
		    move jwscalculator.jar ..\\..\\src\\main\\webapp'''
            }
        }
	stage('JavaPackager生成jar、exe和msi'){
            steps{
                bat '''javapackager -makeall -appclass gitops.jwscalculator.JwsCalculator -name jwscalculator
		    move dist\\bundles\\jwscalculator-1.0.exe src\\main\\webapp
		    move dist\\bundles\\jwscalculator-1.0.msi src\\main\\webapp'''
            }
        }
        stage('打包War') {
            steps {
		   bat '''cd src\\main\\webapp
		      jar cfM jwscalculator.war  *'''
            }
        }
        stage('部署tomcat'){
            steps{
                deploy adapters: [tomcat9(credentialsId: 'tomcat', path: '', url: 'http://localhost:8080')], contextPath: '/jwscalculator', war: 'src/main/webapp/jwscalculator.war'
            }
        }
        stage('本地运行jar'){
            steps{
                bat '''cd src\\main\\webapp
		   java -jar jwscalculator.jar'''
            }
        }
        stage('本地运行jnlp'){
            steps{
                bat '''cd src\\main\\webapp
		   javaws jwscalculator.jnlp'''
            }
        }
        stage('WebStart'){
            steps{
                bat '"C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe" http://localhost:8080/jwscalculator/index.html' 
            }
        }
        stage('清除'){
            steps{
                bat '''rd /S /Q target compiled dist
		    cd src\\main\\webapp
                    del jwscalculator.jar
                    del jwscalculator.war'''
            }
        }
    }   
}
